name: my_lang
description: "A library that provides flexible and easy-to-use localization support for Flutter applications."
version: 1.0.2+3
homepage: https://github.com/ngmduc2012/my_lang.git
funding:
  - https://buymeacoffee.com/ducmng12g
  - https://ko-fi.com/I2I81AEJG8
  - https://github.com/sponsors/ngmduc2012
  - https://paypal.me/ngmduc


environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.2
  intl: ^0.20.2

executables:
  my_lang:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.7
  dart_test_tools: ^6.0.0

flutter:

screenshots:
  - description: "avatar plugin"
    path: avatar.png

topics:
  - localization
  - i18n
  - translation
  - multi-language
  - flutter
